// <auto-generated />
namespace NoorGeneralHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Add_speciality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_speciality));
        
        string IMigrationMetadata.Id
        {
            get { return "202104251016540_Add_speciality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
